---
- name: Install Epel-release
  ansible.builtin.dnf:
    name:
      - epel-release
    state: present
  become: true

- name: Enable PowerTools repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled powertools
  become: true
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

- name: Enable CRB (PowerTools) repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb
  become: true
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '9'

- name: Install Nginx
  ansible.builtin.dnf:
    name:
      - nginx
    state: present
  notify:
    - Enable and start Nginx service
  become: true

- name: Build and install upload module
  import_tasks: build_module.yml
